spring:
  datasource:
    url: jdbc:mysql://${DB_LOCAL_HOST}/google_oauth?serverTimezone=UTC&characterEncoding=UTF-8
    password: ${DB_LOCAL_PASSWORD}
    username: ${DB_LOCAL_USERNAME}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

  main:
    allow-bean-definition-overriding: true

  profiles:
    include: oauth

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 30796921504-plip806b4p5tcnbcl867slfggrvk745d.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

server:
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
